'use client';
import { useState } from "react";
import { MouseEventHandler } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "../../components/RandomFox";
import { random } from "lodash";

const myRandom = () => random(1, 123);

//generate simple unique id
const generateId = () => Math.random().toString(36).substr(2,9)

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();

    const newImageItem: IFoxImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${myRandom()}.jpg`
    }
    setImages([ ...images, newImageItem ])
    //window.plausible("add_fox");
  }

  return (
    <div>
      <Head>
        <title>LazyImage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          data-domain="yourdomain.com"
          src="https://plausible.io/js/script.js"
        ></script>
      </Head>

      <>
      <button onClick={addNewFox}>Add new Fox</button>
        {images.map(({id, url}) => (
          <div className="p-4" key={id}>
            <LazyImage
              src={url}
              title="Random Fox"
              width={320}
              height="auto"
              className="rounded bg-gray-300"
              onClick={() => console.log("hey")} />
          </div>
        ))}
      </>

    </div>
  );
};

export default Home;
